### ISSUE TITLE
Nav disappears on re-size after using dropdown.

### ISSUE THREAD

**Issue by ed-parry** [joshkennedy/zleek#1]
Using the demonstration (http://joshkennedy.github.com/zleek/), if you resize the screen to a mobile view-port, and click on the navigation icon for the drop-down, close it again, and resize the window to a desktop size, the navigation links disappear.

This doesn't happen if you resize the window while the navigation drop-down is active. 

I imagine it's an issue with hiding the navigation to close the bar in mobile, which stays hidden on resize. Not a huge issue -- not exactly a popular use-case.

I'm using Google Chrome 24.0.1312.57, on Windows 7 Ultimate N.

Aside from that, very nice!

**Comment by joshkennedy** [comment]
Thanks @ed-parry - should be fixed now :)

**Comment by ed-parry** [comment]
Brilliant - looking good! :)
