### ISSUE TITLE
Is there a LESS version of the stylesheet?

### ISSUE THREAD

**Issue by bishless** [joshkennedy/zleek#2]
I'm wondering if the css was built via LESS? 

If not, I'll fork and try getting some LESS structure in place for folks that prefer that method.

**Comment by joshkennedy** [comment]
Hey @bishless - I wrote this in plain ol' CSS but you're welcome to port it into any language you desire :+1:

**Comment by bishless** [comment]
Oh, it's 'in progress' up in here!
