### ISSUE TITLE
Homepage in Anchor 0.9

### ISSUE THREAD

**Issue by maman** [joshkennedy/zleek#3]
seems that the "recent post homepage" feature is broken in anchor 0.9.
i've created the page named home, and selecting that as my homepage, but my homepage still shows the default template. is there some missing steps ?

screenshot : 
![homepage](https://f.cloud.github.com/assets/491458/488803/1b6d3cce-b988-11e2-8d9e-568ef4eb4dc9.png)

**Comment by scottfahrig** [comment]
I'm also having the same issue.

**Comment by joshkennedy** [comment]
Should be fixed now :+1:

**Comment by maman** [comment]
many thanks! :+1:
