### ISSUE TITLE
Line Height issue

### ISSUE THREAD

**Issue by scottfahrig** [joshkennedy/zleek#4]
All of my posts are having an obvious line height issue. I've looked at the CSS and can't find a problem.

![zleek-ss](https://f.cloud.github.com/assets/457750/536622/8e9841fa-c15b-11e2-8665-b8ef26ffda66.jpg)

**Comment by filipi777** [comment]
show me an example, I want fix.

**Comment by joshkennedy** [comment]
I opened an issue on the Anchor forums - seems to be an issue with the Markdown rendering inside Zleek - the default them parses the Markdown just fine. Will keep you posted :)

**Comment by joshkennedy** [comment]
Fixed :+1:

**Comment by scottfahrig** [comment]
Thanks!
